PACKAGE_NAME="wyse-3040-audio"
PACKAGE_VERSION="1.0.0"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/sound/soc/intel/boards clean && make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/sound/soc/intel/atom clean"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/sound/soc/intel/boards modules && make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/sound/soc/intel/atom modules"

BUILT_MODULE_NAME[0]="snd-soc-sst-cht-bsw-rt5672"
BUILT_MODULE_LOCATION[0]="sound/soc/intel/boards/"
DEST_MODULE_LOCATION[0]="/kernel/sound/soc/intel/boards/"

BUILT_MODULE_NAME[1]="snd-soc-sst-atom-hifi2-platform"
BUILT_MODULE_LOCATION[1]="sound/soc/intel/atom/"
DEST_MODULE_LOCATION[1]="/kernel/sound/soc/intel/atom/"

AUTOINSTALL="yes"
